const black = {
  css: {
    '--tw-prose-body': 'var(--black)',
    '--tw-prose-headings': 'var(--black)',
    '--tw-prose-lead': 'var(--black)',
    '--tw-prose-links': 'var(--black)',
    '--tw-prose-bold': 'var(--black)',
    '--tw-prose-counters': 'var(--black)',
    '--tw-prose-bullets': 'var(--black)',
    '--tw-prose-hr': 'var(--black)',
    '--tw-prose-quotes': 'var(--black)',
    '--tw-prose-quote-borders': 'var(--black)',
    '--tw-prose-captions': 'var(--black)',
    '--tw-prose-code': 'var(--black)',
    '--tw-prose-pre-code': 'var(--black)',
    '--tw-prose-pre-bg': 'var(--black)',
    '--tw-prose-th-borders': 'var(--black)',
    '--tw-prose-td-borders': 'var(--black)',
    '--tw-prose-invert-body': 'var(--black)',
    '--tw-prose-invert-headings': 'var(--black)',
    '--tw-prose-invert-lead': 'var(--black)',
    '--tw-prose-invert-links': 'var(--black)',
    '--tw-prose-invert-bold': 'var(--black)',
    '--tw-prose-invert-counters': 'var(--black)',
    '--tw-prose-invert-bullets': 'var(--black)',
    '--tw-prose-invert-hr': 'var(--black)',
    '--tw-prose-invert-quotes': 'var(--black)',
    '--tw-prose-invert-quote-borders': 'var(--black)',
    '--tw-prose-invert-captions': 'var(--black)',
    '--tw-prose-invert-code': 'var(--black)',
    '--tw-prose-invert-pre-code': 'var(--black)',
    '--tw-prose-invert-pre-bg': 'rgb(0 0 0 / 50%)',
    '--tw-prose-invert-th-borders': 'var(--black)',
    '--tw-prose-invert-td-borders': 'var(--black)',
  },
};

export default black;
